image:
  file: .gitpod.Dockerfile
  
ports:
  - name: Web App
    description: The main application web server
    port: 8080
    visibility: public
  
vscode:
  extensions:
    - denoland.vscode-deno
    - github.github-vscode-theme
#tasks:
#  - before: d="$HOME/.slack"; md="/workspace/${d##*/}"; mkdir -p "$md" && rm -rf "$d" && ln -sf "$md" "$d" && exit
